### ISSUE TITLE
cli-table to format the console output

### ISSUE THREAD

**Issue by pankajpatel** [watson/code-status#4]
Hi,

I was trying to build [similar tool](https://www.npmjs.com/package/list-repos). And this repo is exactly what I intend to build.

Though the output of the tool can be more formatted with [chalk](https://www.npmjs.com/package/chalk) and [cli-table](https://www.npmjs.com/package/cli-table)

I would like to contribute on this.

**Comment by watson** [comment]
Thanks for the contribution 😃 

Now that your PR have been merged and published I'm going to close this issue
